Repository BurhanH/TestAutomationCourse-python-ui-project, pull requests merged in 2022-06, with the labels that each got.

#18 Zr my test
  tests/test_tools_qa_zr.py
Labels: enhancement

#22 SA-TC :: Add tests for frames
  tests/test_toolsqa_frames.py
  tests/test_toolsqa_nested_frames.py
Labels: enhancement

#21 Add tests for Accordian
  tests/test_accordian.py
Labels: enhancement

#25 refactoring and adding: test_success_log_out, test_failed_login
  tests/test_saucedemo_e2e_tests.py
Labels: enhancement

#26 Tests on autorization with empty fields, problem_user, lock_out_user and performance_glitch user
  tests/test_saucedemo_autorization_and_order.py
Labels: enhancement

#30 SA-RF :: Change setUp method
  tests/test_accordian.py
  tests/test_date_picker.py
  tests/test_saucedemo_autorization_and_order.py
  tests/test_saucedemo_e2e_tests.py
  tests/test_tools_qa.py
  tests/test_tools_qa_zr.py
  tests/test_toolsqa_alerts.py
  tests/test_toolsqa_frames.py
  tests/test_toolsqa_modal_dialogs.py
  tests/test_toolsqa_nested_frames.py
  utils/base_test.py
Labels: enhancement, refactoring

#29 First draft version
  .github/workflows/run_tests.yml
  README.md
  pytest.ini
  requirements.txt
  tests/test_dummy.py
Labels: enhancement

#32 SA-TC :: Add test toolsqa dynamic properties
  pytest.ini
  tests/test_dynamic_prpperties.py
Labels: enhancement

#12 Сценарии для автотестов и 1 автотест
  Check_CRUD_element.txt
  tests/test_project_python_04.py
Labels: enhancement

#34 SA-RF :: Refactoring SauceDemo login tests, POM
  model/__init__.py
  model/saucedemo/__init__.py
  model/saucedemo/home_page_logged_in.py
  model/saucedemo/home_page_logged_out.py
  pytest.ini
  requirements.txt
  tests/test_saucedemo_authorization.py
  tests/test_saucedemo_autorization_and_order.py
  tests/test_saucedemo_order.py
Labels: enhancement, refactoring

#35 SA-TC :: Add tests for uploading and downloading files
  .gitignore
  resources/data.py
  resources/downloads_folder/.placeholder
  resources/file_sample/SampleForJPG.jpg
  tests/test_download_upload_file.py
  utils/project_utils.py
  utils/screenshot_utils.py
Labels: enhancement, refactoring

#37 SA-RF :: Fix failing test download file
  tests/test_download_upload_file.py
Labels: refactoring

#39 Added pylint static code analyzer.
  .github/workflows/code-standard-checker.yml
  README.md
  requirements.txt
  tests/test_toolsqa_elements_zr.py
Labels: enhancement

#40 code standard badge
  README.md
Labels: enhancement
