Repository BurhanH/TestAutomationCourse-python-ui-project, pull requests merged in 2022-05, with the labels that each got.

#4 Update README.md
  README.md
Labels: documentation

#5 Tests added
  tests/test_tools_qa.py
Labels: enhancement

#7 SA-RF :: Refactor test_tools_qa
  .gitignore
  tests/test_tools_qa.py
Labels: refactoring

#8 SA-TC :: Add tests for alerts
  tests/test_dummy.py
  tests/test_toolsqa_alerts.py
Labels: enhancement

#11 VK-TC :: Add tests for Modal dialogs
  tests/test_toolsqa_modal_dialogs.py
Labels: enhancement

#16 SA-RF :: Add BaseTest class
  tests/__init__.py
  tests/test_date_picker.py
  tests/test_dummy.py
  tests/test_saucedemo_e2e_tests.py
  tests/test_tools_qa.py
  tests/test_toolsqa_alerts.py
  tests/test_toolsqa_modal_dialogs.py
  utils/__init__.py
  utils/base_test.py
Labels: enhancement, refactoring
